//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models.Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> KartelaId { get; set; }
        public Nullable<int> KartelaModelId { get; set; }
        public string Cila { get; set; }
        public string Description { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> KaporaPrice { get; set; }
        public string KaporaType { get; set; }
        public string PaymentType { get; set; }
    }
}
