//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models.Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> KartelaId { get; set; }
        public Nullable<int> KartelaModelId { get; set; }
        public string Cila { get; set; }
        public string Description { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> KaporaPrice { get; set; }
        public string KaporaType { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> ProductId2 { get; set; }
        public Nullable<int> ModelId2 { get; set; }
        public Nullable<int> KartelaModelId2 { get; set; }
        public string Cila2 { get; set; }
        public string Description2 { get; set; }
        public Nullable<int> ProductId3 { get; set; }
        public Nullable<int> ModelId3 { get; set; }
        public Nullable<int> KartelaModelId3 { get; set; }
        public string Cila3 { get; set; }
        public string Description3 { get; set; }
        public Nullable<int> ProductId4 { get; set; }
        public Nullable<int> ModelId4 { get; set; }
        public Nullable<int> KartelaModelId4 { get; set; }
        public string Cila4 { get; set; }
        public string Description4 { get; set; }
        public Nullable<int> KartelaId2 { get; set; }
        public Nullable<int> KartelaId3 { get; set; }
        public Nullable<int> KartelaId4 { get; set; }
    }
}
