//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models.Types
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModel
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ModelName { get; set; }
    }
}
